ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'WORK_LOG_DRAFT';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'WORK_LOG_COMPLETED';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'WORK_LOG_ADMIN_UPDATED';
